### ISSUE TITLE
返回码：1

### ISSUE THREAD

**Issue by Coriginbe** [Justin62628/Squirrel-RIFE#409]
[导出设置预览]

任务参数预览：
SVFI版本：0.0.3
[基本信息]
输出文件夹：C:/Users/Honry/Desktop 
输入帧率：23.09701 
输出帧率：46.19401 
输出格式：mov 
导出带音频字幕：False
补帧倍率：1
风险模式：False
[工作状态恢复]
补帧时刻：00:00:00 - 00:00:00
起始区块：-1 起始输入帧：-1
[转场识别与动漫优化]
关闭转场识别：False 
转场识别参数：12 
转场使用帧混合：False 
输出转场帧：False
使用固定转场识别：False 
固定转场识别参数：40
重复帧去除模式：0
[输出分辨率]
宽：1920 高：1080
黑边长度 - 宽：0 高：0
使用AI超分：True
使用的超分算法：realCUGAN
使用的超分模型：up2x-latest-conservative.pth
超分切割模式：200
超分切割块大小：200
超分半精度：True
超分转移分辨率模式：0
[输出质量控制]
渲染质量crf：16
目标码率：90.0
编码器：H265,8bit 
压制编码预设：fast 
N卡硬编预设：None
使用默认编码模式：False
高精度工作流：True
使用快速拆帧：False
HDR模式：0 
硬件解码：True 
指定编码线程数：False
开启反交错：False 
开启快速降噪：False
输出区块大小：1000 帧
手动指定缓冲区内存：1G
开启时间重映射：False 帧率 = fps
自定义压制参数：
[补帧参数]
半精度模式：False 
双向光流：True 
反向光流：False 
动态光流尺度：False
固定光流尺度：1.00
使用的补帧模型：
TTA：模式 = 0 代数 = 1
用于补帧的N卡：-1
使用NCNN补帧：True
NCNN补帧线程数：4
NCNN选择的GPU：0
使用多卡：False
N卡计数：0

app_dir => C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package
crop_height => 0
crop_width => 0
debug => False
encode_audio_checker => False
gif_loop => True
gui_inputs => {"inputs": [{"task_id": "c8a_890723", "input_path": "C:/Users/Honry/Desktop/video.mp4"}]}
hdr_cube_index => 0
hdr_mode => 0
input_end_point => 00:00:00
input_fps => 23.09701
input_start_point => 00:00:00
interp_start => -1
is_16bit_workflow => True
is_encode_audio => False
is_exp_prior => True
is_img_output => False
is_keep_head => False
is_no_scdet => False
is_output_only => True
is_quick_extract => False
is_render_slow_motion => False
is_rife_reverse => False
is_save_audio => False
is_scdet_mix => False
is_scdet_output => False
manual_buffer_size => 1
ncnn_gpu => 0
ncnn_thread => 4
no_concat => False
output_chunk_cnt => -1
output_dir => C:/Users/Honry/Desktop
output_ext => mov
pos => PyQt5.QtCore.QPoint(3, 33)
remove_dup_mode => 0
remove_dup_threshold => 10.0
render_bitrate => 90.0
render_crf => 16
render_encode_thread => 16
render_encoder => H265,8bit
render_encoder_preset => fast
render_ffmpeg_customized => 
render_gap => 1000
render_hwaccel_mode => CPU
render_hwaccel_preset => None
render_slow_motion_fps => 
resize_exp => 2.0
resize_height => 1080
resize_settings_index => 8
resize_width => 1920
rife_cuda_cnt => 0
rife_exp => 1
rife_interlace_inference => 0
rife_interp_before_resize => 100
rife_model => 
rife_model_name => 
rife_scale => 1.00
rife_tta_iter => 1
rife_tta_mode => 0
risk_resume_mode => False
scdet_fixed_max => 40
scdet_flow_cnt => 0
scdet_mode => 0
scdet_threshold => 12
size => PyQt5.QtCore.QSize(634, 714)
sr_module_exp => 2
sr_realcugan_tilemode => 3
sr_tilesize => 200
sr_tilesize_mode => 0
target_fps => 46.19401
transfer_ratio_index => 0
use_bitrate => False
use_crf => True
use_dedup_sobel => False
use_deinterlace => False
use_evict_flicker => False
use_fast_denoise => False
use_hwaccel_decode => True
use_manual_buffer => False
use_manual_encode_thread => False
use_ncnn => True
use_realesr_fp16 => True
use_render_avx512 => False
use_render_encoder_default_preset => False
use_render_zld => False
use_rife_auto_scale => False
use_rife_forward_ensemble => True
use_rife_fp16 => False
use_rife_multi_cards => False
use_scdet_fixed => False
use_specific_gpu => -1
use_sr => True
use_sr_algo => realCUGAN
use_sr_mode => 0
use_sr_model => up2x-latest-conservative.pth
version => 0.0.3

[设置信息]

[Squirrel Anime Enhance 0.0.3 仅渲染操作启动]
2022-07-02 16:43:56,680 - one_line_shot_args - 241 - INFO - Initial New Interpolation Project: PROJECT DIR: C:/Users/Honry/Desktop\video_c8a_890723, INPUT FILEPATH: C:/Users/Honry/Desktop/video.mp4
2022-07-02 16:44:02,883 - utils - 1233 - INFO - Auto Find FPS in r_frame_rate: 23.083333333333332
2022-07-02 16:44:02,887 - utils - 1244 - INFO - Auto Find Frames Cnt by duration deduction: 3853
2022-07-02 16:44:03,183 - one_line_shot_args - 149 - INFO - Render only, target fps is changed to input fps: 23.083333333333332
2022-07-02 16:44:03,492 - one_line_shot_args - 182 - INFO - Free RAM: 0.8G, Update Task Queue Len: 8, Duplicate Frames Cnt Upper Limit: 12
2022-07-02 16:44:03,498 - one_line_shot_args - 111 - INFO - Check Input Source: FPS: 23.083333333333332 -> 23.083333333333332, FRAMES_CNT: 3853, INTERP_TIMES: 1, HDR: CUSTOM_HDR, FRAME_SIZE: (1080, 1920), QUEUE_LEN: 8, INPUT_EXT: .mp4, OUTPUT_EXT: .mov
C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:100.)
return torch._C._cuda_getDeviceCount() > 0
2022-07-02 16:44:26,149 - one_line_shot_args - 1988 - INFO - Load Super Resolution Module at realCUGAN, Model at up2x-latest-conservative.pth, Transfer Mode = HALF, scale = 2
2022-07-02 16:44:26,153 - one_line_shot_args - 2019 - INFO - Start Super Resolution VRAM Test: 540x960
2022-07-02 16:44:26,200 - one_line_shot_args - 802 - INFO - Activate Any-FPS Mode without Dedup/Scene Detection)
2022-07-02 16:44:26,222 - one_line_shot_args - 432 - INFO - Resuming Checkpoint...
2022-07-02 16:44:29,138 - one_line_shot_args - 2027 - ERROR - SR VRAM Check Failed, PLS Lower your transfer resolution or tilesize for RealESR

[LAST ERROR MSG in OLS]:
return torch._C._cuda_getDeviceCount() > 0
2022-07-02 16:44:26,149 - one_line_shot_args - 1988 - INFO - Load Super Resolution Module at realCUGAN, Model at up2x-latest-conservative.pth, Transfer Mode = HALF, scale = 2
2022-07-02 16:44:26,153 - one_line_shot_args - 2019 - INFO - Start Super Resolution VRAM Test: 540x960
2022-07-02 16:44:26,200 - one_line_shot_args - 802 - INFO - Activate Any-FPS Mode without Dedup/Scene Detection)
2022-07-02 16:44:26,222 - one_line_shot_args - 432 - INFO - Resuming Checkpoint...
2022-07-02 16:44:29,138 - one_line_shot_args - 2027 - ERROR - SR VRAM Check Failed, PLS Lower your transfer resolution or tilesize for RealESR
Traceback (most recent call last):
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\one_line_shot_args.py", line 2022, in vram_test
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\Utils\utils.py", line 1745, in wrapper
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 696, in svfi_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 701, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 171, in enhance
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 80, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 662, in model_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 289, in forward
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\functional.py", line 3570, in _pad
return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: "reflection_pad2d" not implemented for 'Half'

2022-07-02 16:44:29,139 - one_line_shot_args - 2092 - CRITICAL - Super Resolution Thread Panicked

[LAST ERROR MSG in OLS]:
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\one_line_shot_args.py", line 2022, in vram_test
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\Utils\utils.py", line 1745, in wrapper
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 696, in svfi_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 701, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 171, in enhance
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 80, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 662, in model_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 289, in forward
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\functional.py", line 3570, in _pad
return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: "reflection_pad2d" not implemented for 'Half'

2022-07-02 16:44:29,139 - one_line_shot_args - 2092 - CRITICAL - Super Resolution Thread Panicked
2022-07-02 16:44:29,141 - one_line_shot_args - 2093 - CRITICAL - Traceback (most recent call last):
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\one_line_shot_args.py", line 2049, in run
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\one_line_shot_args.py", line 2022, in vram_test
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\Utils\utils.py", line 1745, in wrapper
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 696, in svfi_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 701, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 171, in enhance
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\autograd\grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\CudaResolutionModule.py", line 80, in process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 662, in model_process
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\modules\module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\SuperResolution\RealCUGANModule.py", line 289, in forward
File "C:\Users\Honry\DOWNLO~1\SAE00~1.3\Package\torch\nn\functional.py", line 3570, in _pad
return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: "reflection_pad2d" not implemented for 'Half'

2022-07-02 16:44:29,296 - one_line_shot_args - 1601 - WARNING - Renamed Chunk Not found: C:/Users/Honry/Desktop\video_c8a_890723\chunk-tmp.mov
2022-07-02 16:44:35,500 - one_line_shot_args - 805 - INFO - Input Frames loaded
2022-07-02 16:44:35,593 - one_line_shot_args - 2111 - WARNING - Detect that Task Complete Progress Rate (now frame / all frame cnt) is lower than 80%, Please Check whether Your Disk of input file was disconnected during the process and check whether output file exists and is in full length!
2022-07-02 16:44:35,593 - one_line_shot_args - 2398 - ERROR - 
Program Failed at 2022-07-02 16:44:35.593810: Duration: 0:00:32.094969
Program Failed at 2022-07-02 16:44:35.593810: Duration: 0:00:32.094969
[LAST ERROR MSG in OLS]:

0%| | 0/3853 [00:00<?, ?frames/s]2022-07-02 16:44:35,593 - one_line_shot_args - 2111 - WARNING - Detect that Task Complete Progress Rate (now frame / all frame cnt) is lower than 80%, Please Check whether Your Disk of input file was disconnected during the process and check whether output file exists and is in full length!
2022-07-02 16:44:35,593 - one_line_shot_args - 2398 - ERROR - 

Program Failed at 2022-07-02 16:44:35.593810: Duration: 0:00:32.094969
100%|##########| 3853/3853 [00:00<00:00, 1923887.30frames/s]
INFO - ONE LINE SHOT ARGS 0.0.3 2022-07-02
Warning: Find Empty Arguments at 'render_ffmpeg_customized'
Warning: Find Empty Arguments at 'render_slow_motion_fps'
Warning: Find Empty Arguments at 'rife_model'
Warning: Find Empty Arguments at 'rife_model_name'

INFO - 2022-07-02 16:44:36.781576 C:/Users/Honry/Desktop/video.mp4 完成

**Comment by Justin62628** [comment]
试试关闭超分半精度

**Comment by Coriginbe** [comment]
Confirm Start Info：输出文件格式与源不相同
文件输出格式(!) 只有mov选项

**Comment by Justin62628** [comment]
以后会添加多种输出格式
