### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [Justin62628/Squirrel-RIFE#421]
Unable to start mission
SVFI不支持当前系统环境，请更换设备

[LAST ERROR MSG in OLS]:
Traceback (most recent call last):
File "D:\Program Files\Steam\steamapps\common\SVFI\UI\SVFI_Backend.py", line 363, in run
File "D:\Program Files\Steam\steamapps\common\SVFI\subprocess.py", line 800, in __init__
File "D:\Program Files\Steam\steamapps\common\SVFI\subprocess.py", line 1207, in _execute_child
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

该报错是点击一键压制/补帧/超分按钮后，一瞬间就出现的报错，疑似subprocess出现问题
ols所有功能正常

**Comment by Justin62628** [comment]
SVFI 3.19.25-alpha
